import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from "../components/NavBar"
import Footer from "../components/Footer"
import location from "../public/location_on.png"
import timer from "../public/timer.png"

import {
  Box,
  Button,
  Flex,
  Image,
  Heading,
  Stack,
  Text,
  HStack,
  VStack,
  Link
} from "@chakra-ui/react";
import Header from '../components/Header1'

const DATE = new Date(2023, 1, 26)

function getTimeRemaining(endtime: Date){
  const total = -(-endtime) / 1 - Date.now();
  const seconds = Math.floor( (total/1000) % 60 );
  const minutes = Math.floor( (total/1000/60) % 60 );
  const hours = Math.floor( (total/(1000*60*60)) % 24 );
  const days = Math.floor( total/(1000*60*60*24) );
    console.log(endtime.getMilliseconds())
  return {
    total,
    days,
    hours,
    minutes,
    seconds
  };
}

export default function Home() {
  return (
    <>
      <Navbar />

      <Header />

      <Flex
      align="center"
      justify={{ base: "center" }}
      direction={{ base: "column-reverse", md: "row" }}
      wrap="nowrap"
      minH="30vh"
      px={8}
      bgSize="cover"
      bgColor="brand2.400"
      >
        <VStack>
        <HStack m={10}>
        <Image src='location_on.png' alt='Location' maxW={100}/>
        <Heading
        as="h3"
        size="lg"
        
        >7171 rue Saint-laurent, H8J 4K1, Montréal, QC, CA</Heading> 
        
        </HStack>
        <HStack m={10}>
        <Image src='timer.png' alt='Location' maxW={100}/>
        <Heading
        as="h3"
        size="lg"
        
        >{getTimeRemaining(new Date(2023, 1, 26)).days} Days to go</Heading> 
        
        </HStack>
        <HStack
        >
        <Heading 
        w={"40vw"} 
        mt={10}
        mb={20}
        py={10}
        bgColor="brand2.800"
        as="h4"
        size="lg"
        textAlign="center"
        borderRadius={10}

        ><Link  href="./infos" >Plus d'infos</Link></Heading>
        </HStack>
        </VStack>
        
        
        
      </Flex>

      <Footer></Footer>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </>
  )

  
}
