FROM node:14.17.0-alpine3.12

WORKDIR /app
COPY package.json yarn.lock tsconfig.json  tsconfig.build.json ./
RUN yarn install --ignore-platform
COPY . .
RUN yarn build
EXPOSE 3000
CMD ["yarn", "start:prod"]


