### STAGE 1: Build ###
FROM node:14.17.0-alpine3.12 AS build
WORKDIR /usr/src/app
COPY package.json yarn.lock tsconfig.json tsconfig.app.json tsconfig.spec.json ./
RUN yarn install
COPY . .
RUN yarn build:prod

### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/cqi-2023 /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]